Repository facebookexperimental/libunifex, pull requests merged in 2023-10, with the labels that each got.

#565 fix cancellation lifetime issue in `type_erased_stream`
  include/unifex/type_erased_stream.hpp
  test/type_erase_test.cpp
Labels: CLA Signed

#566 fix shadowed `refCount_` member in `type_erased_stream`
  include/unifex/type_erased_stream.hpp
Labels: bug, CLA Signed

#568 Add <iterator> to when_all_range.hpp
  include/unifex/when_all_range.hpp
Labels: CLA Signed

#534 add cancellation support into `io_uring_context`
  include/unifex/linux/io_uring_context.hpp
  test/io_uring_2_test.cpp
Labels: CLA Signed

#570 add http server example with `io_uring`
  examples/linux/http_server_io_uring_test.cpp
Labels: documentation

#571 add clang-13...clang-16
  .github/workflows/libunifex-ci.yml
Labels: CLA Signed

#572 fix branch name `main` in README.md
  README.md
Labels: CLA Signed

#575 add clang-17
  .github/workflows/libunifex-ci.yml
Labels: CLA Signed

#576 rm gcc-9, gcc-10, clang-10, clang-11
  .github/workflows/libunifex-ci.yml
  README.md
  include/unifex/config.hpp.in
  include/unifex/v1/async_scope.hpp
Labels: CLA Signed

#579 Fix UB in cancelled tasks again
  include/unifex/task.hpp
  test/task_scheduler_affinity_test.cpp
Labels: CLA Signed

#581 Clang format win32
  include/unifex/win32/detail/ntapi.hpp
  include/unifex/win32/detail/safe_handle.hpp
  include/unifex/win32/detail/types.hpp
  include/unifex/win32/filetime_clock.hpp
  include/unifex/win32/low_latency_iocp_context.hpp
  include/unifex/win32/windows_thread_pool.hpp
  source/win32/filetime_clock.cpp
  source/win32/low_latency_iocp_context.cpp
  source/win32/ntapi.cpp
  source/win32/safe_handle.cpp
  source/win32/windows_thread_pool.cpp
Labels: CLA Signed
